print('')
print('Olá eu sou um conversor de metro (m) em centimetros (cm) e milimetros (mm)')
name = input('Qual o seu nome? ')
print('')
print('É um prazer te conhecer {}'.format(name))
print('')
m = float(input('Certo! Agora o valor que deseja converter em cm e mm: '))
print('')
print('Pronto! {} o valor {} m em centimetros é {} cm e em milimetros é {} mm.'.format(name, m, m*100, m*1000))