print('')
print('')
print('Olá eu sou uma calculadora de médias!')
print('')
nome = input('Como você se chama? ')
print('')
print('É um prazer te conhecer {}'.format(nome))
print('')
not1 = float(input('Digite aqui a sua primeira nota: '))
print('')
not2 = float(input('Digite aqui a sua segunda nota: '))
print('')
print('A sua média, {}, é de {:.2f}.'.format(nome, (not1+not2)/2))