print('')
print('{:=^125}'.format('Operadores Aritiméticos'))
print('')
print('Operações Básicas')
print('  |-->Soma = (+)')
print('  |-->Subtração = (-)')
print('  |-->Multiplicação = (*)')
print('  |-->Divisão = (/)')
print('')
print('Operações + Complexas')
print('  |-->Potenciação = (**)')
num1 = int(input('Digite aqui um número: '))
num2 = int(input('Digite aqui a potência que deseja elevar o número anterior: '))
pot = (num1**num2)
print('O resultado é {}.'.format(pot,num1,num2,num1))
print('')
print('  |-->Divisão exata = (//)')
num3 = int(input('Digite um número: '))
print('')
num4 = int(input('Digite um número para dividir o primeiro: '))
div = (num3//num4)
print('')
print('O número inteiro da divisão de {} por {} é igual a {}'.format(num3,num4,div))
print('')
print('  |-->Resto da divisão = (%)')
num5 = int(input('Digite um número: '))
print('')
num6 = int(input('Digite um número para dividir o primeiro: '))
rest = (num5%num6)
print('')
print('O resto da divisão de {} por {} é {}.'.format(num5,num6,rest))
