print('')
print('')
thing = input('Digite alguma coisa: ')
print('')
print('Qual é a classe de {}'.format(thing),type(thing))
print('{} é alfanumérico:'.format(thing),thing.isalnum())
print('{} faz parte do alfabeto:'.format(thing),thing.isalpha())
print('{} é um código binário:'.format(thing),thing.isascii())
print('{} é um decimal:'.format(thing),thing.isdecimal())
print('{} é um digito:'.format(thing),thing.isdigit())
print('{} é identificavel:'.format(thing),thing.isidentifier())
print('{} é minúscula:'.format(thing),thing.islower())
print('{} é um número:'.format(thing),thing.isnumeric())
print('{} é "imprimivel:"'.format(thing),thing.isprintable())
print('{} é um espaço:'.format(thing),thing.isspace())
print('{} é um título:'.format(thing),thing.istitle())
print('{} é maiúscula:'.format(thing),thing.isupper())
